### ISSUE TITLE
How to use HTTP_LOCATION correctly?

### ISSUE THREAD

**Issue by jreimone** [crramirez/limesurvey#16]
Hi,
my URL is supposed to be `https://my.server.net/surveys`. So my docker-compose config looks like this:

```
   limesurvey:
      restart: always
      image: crramirez/limesurvey:2.72.3
      links:
        - "mysql:db"
      expose:
        - "80"
      environment:
        - "DISABLE_MYSQL=yes"
        - "HTTP_LOCATION=surveys"
      volumes:
        - "./limesurvey/upload:/app/upload"
        - "./limesurvey/config/config-defaults.php:/app/application/config/config-defaults.php"
```
But when I request `https://my.server.net/surveys` in the browser I always get redirected to `https://my.server.net/index.php?r=installer`. What am I doing wrong?

**Comment by crramirez** [comment]
Hello,

Check your docker-compose.yml you are using expose instead of ports:

```
   limesurvey:
      restart: always
      image: crramirez/limesurvey:2.72.3
      links:
        - "mysql:db"
      ports:
        - "80:80"
      environment:
        - "DISABLE_MYSQL=yes"
        - "HTTP_LOCATION=surveys"
      volumes:
        - "./limesurvey/upload:/app/upload"
        - "./limesurvey/config/config-defaults.php:/app/application/config/config-defaults.php"
```

Probably you have another instance running and it is who is answering you.
