### ISSUE TITLE
Error whe I try to configure database mysql

### ISSUE THREAD

**Issue by m4rky77** [crramirez/limesurvey#32]
Hi, 

I try to configure the database, with separate mysql docker-compose, how the readme file say , but when I press next the installer show me the follow error:

 

> SQLSTATE[HY000] [2059] Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory

Regards

**Comment by crramirez** [comment]
Well the problem is that the plugin for PHP installed in the image is not compatible with MySQL 8. As with limesurvey 4 I need to redo the image to support the latest ubuntu and php7. For now I limited the version for MySQL to 5 in the docker-compose.yml:

```yml
...
services:
  mysql:
    image: mysql:5
    volumes:
      - mysql:/var/lib/mysql
    restart: always
...
```

You must delete everything in order for this change work in your containers with:

```bash
docker-compose down --volumes
```

Regards,
Carlos
