### ISSUE TITLE
LimeSurvey behind traefik proxy

### ISSUE THREAD

**Issue by stefangweichinger** [crramirez/limesurvey#34]
trying this docker-compose.yml:

```
version: '2'

services:

  limesurvey:
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    image: crramirez/limesurvey:latest
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:survey.mydomain.com"
      - "traefik.port=80"
volumes:
  mysql:
  upload:
```

and it always times out.

logs of container show:

```
# docker-compose up 
Recreating limesurvey_limesurvey_1 ... done
Attaching to limesurvey_limesurvey_1
limesurvey_1  | => Using an existing volume of MySQL
limesurvey_1  | /usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
limesurvey_1  |   'Supervisord is running as root and it is searching '
limesurvey_1  | 2019-07-25 14:30:34,290 CRIT Supervisor running as root (no user in config file)
limesurvey_1  | 2019-07-25 14:30:34,295 WARN Included extra file "/etc/supervisor/conf.d/supervisord-mysqld.conf" during parsing
limesurvey_1  | 2019-07-25 14:30:34,296 WARN Included extra file "/etc/supervisor/conf.d/supervisord-apache2.conf" during parsing
limesurvey_1  | 2019-07-25 14:30:34,385 INFO RPC interface 'supervisor' initialized
limesurvey_1  | 2019-07-25 14:30:34,391 CRIT Server 'unix_http_server' running without any HTTP authentication checking
limesurvey_1  | 2019-07-25 14:30:34,392 INFO supervisord started with pid 7
limesurvey_1  | 2019-07-25 14:30:35,396 INFO spawned: 'mysqld' with pid 11
limesurvey_1  | 2019-07-25 14:30:35,400 INFO spawned: 'apache2' with pid 12
limesurvey_1  | 2019-07-25 14:30:36,773 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
limesurvey_1  | 2019-07-25 14:30:36,774 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

anything particular to do here?
thanks
